#!/bin/bash

CONFIG_DIR=$(git rev-parse --show-toplevel)
source "${CONFIG_DIR}/src/utils.sh"

print_title "DEVELOPER TOOLING"

# CLI utilities
print_subtitle "Installing CLI utilities..."
brew__install "fd"
brew__install "glow"
brew__install "gum"
brew__install "htop"
brew__install "neovim"
brew__install "vim"
brew__install "tig"
brew__install "tmux"
brew__install "screen"
brew__install "zoxide"
brew__install "wget"
brew__install "watch"
brew__install "rsync"
brew__install "tree"
brew__install "telnet"
brew__install "mtr"
brew__install "speedtest-cli"
brew__install "websocat"
brew__install "yq"
brew__install "xmlstarlet"
brew__install "pandoc"
brew__install "difftastic"
brew__install "pwgen"

# GNU coreutils & friends
print_subtitle "Installing GNU tooling..."
brew__install "awk"
brew__install "gnu-sed"
brew__install "gnu-tar"
brew__install "gnu-which"
brew__install "gnu-indent"
brew__install "findutils"
brew__install "diffutils"
brew__install "grep"
brew__install "binutils"
brew__install "ed"
brew__install "less"
brew__install "gzip"
brew__install "unzip"
brew__install "sevenzip"
brew__install "wdiff"
brew__install "md5deep"

# Git tooling
print_subtitle "Installing Git tooling..."
brew__install "git"
brew__install "git-delta"
brew__install "git-lfs"
brew__install "git-filter-repo"
brew__install "hub"

# Languages & runtimes
print_subtitle "Installing languages & runtimes..."
brew__install "node"
brew__install "nvm"
brew__install "uv"
brew__install "pipx"
brew__install "pyenv"
brew__install "rbenv"
brew__install "rustup"
brew__install "rust"
brew__install "sbt"
brew__install "maven"
brew__install "openjdk@17"
brew__install "openjdk@21"
brew__install "clj-kondo"
brew__install "eca"

# Containers, cloud & infra
print_subtitle "Installing containers, cloud & infra..."
brew__install "docker"
brew__install "docker-compose"
brew__install "docker-buildx"
brew__install "colima"
brew__install "qemu"
brew__install "kubernetes-cli"
brew__install "kubectx"
brew__install "redis"
brew__install "teleport"
brew__install "tektoncd-cli"
brew__install "telegraf"
brew__install "grafana"
brew__cask "gcloud-cli"
brew__cask "temurin@11"

# AWS & auth
print_subtitle "Installing AWS & auth tooling..."
brew__install "awscli"
brew__install "aws-iam-authenticator"
brew__install "gimme-aws-creds"
brew__install "ykman"

# Media / docs processing
print_subtitle "Installing media & doc tooling..."
brew__install "ffmpeg"
brew__install "imagemagick"
brew__install "ghostscript"
brew__install "graphviz"
brew__install "poppler"
brew__install "mkdocs-material"

# Misc
print_subtitle "Installing misc..."
brew__install "ollama"
brew__install "ansible"
brew__install "sonar-scanner"
brew__install "spotify_player"
