"$schema" = 'https://starship.rs/config-schema.json'

format = """
[󰄛](fg:pink)\
$directory\
$git_branch\
$git_status\
$time\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_frappe'

[directory]
# style = "bg:prev_bg fg:crust"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[cmd_duration]
show_milliseconds = true
format = " in $duration "
# style = "bg:prev_fg"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bg:prev_bg"

[git_branch]
# style = "bg:prev_bg fg:crust"
symbol = ""

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
conflicted = '⚠${count}'
stashed = '!${count}'
staged = '+${count}'    # (+) new & modified fils in the staging area
deleted = '-${count}'   # (-) deleted files in the staging area
renamed = '>>${count}'   # (») renamed files in the staging area
modified = '~${count}'  # (~) modified files in the working directory
untracked = '?${count}' # (?) untracked files in the working directory

[time]
disabled = false
time_format = "%R"

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[os]
disabled = false
# style = "bg:prev_bg fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"


[aws]
disabled = true
[ruby]
disabled = true
[java]
disabled = true
[nodejs]
disabled = true
[c]
disabled = true
[rust]
disabled = true
[golang]
disabled = true
[php]
disabled = true
[kotlin]
disabled = true
[haskell]
disabled = true
[python]
disabled = true
[docker_context]
disabled = true
[conda]
disabled = true

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

